rede-social-de-carros/Models/Endereco.cs
namespace rede_social_de_carros.Models
{
    public class Endereco
    {
        public int Id { get; set; }
        public string Cep { get; set; }
        public string Logradouro { get; set; }
        public string Bairro { get; set; }
        public string Localidade { get; set; }
    }
}

rede-social-de-carros/Controllers/EnderecosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using rede_social_de_carros.Data;
using rede_social_de_carros.Models;
using rede_social_de_carros.Services;

namespace rede_social_de_carros.Controllers
{
    [Authorize]
    public class EnderecosController : Controller
    {
        public readonly EnderecoService _enderecoService;
        public readonly UsuarioService _usuarioService;
        private readonly IHttpClientFactory _httpClientFactory;

        public EnderecosController(EnderecoService enderecoService, IHttpClientFactory httpClientFactory, UsuarioService usuarioService)
        {
            _enderecoService = enderecoService;
            _httpClientFactory = httpClientFactory;
            _usuarioService = usuarioService;
        }

        // GET: Enderecos
        public async Task<IActionResult> Index()
        {

            var usuario = _usuarioService.ObterTodos().Result.Find(u => u.Email == User.Identity.Name);
            var address = _enderecoService.ObterTodos()
                .Result
                .Where(a => a.Id == usuario.EnderecoId);
            return View(address);
        }

        // GET: Enderecos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || await _enderecoService.ObterTodos() == null)
            {
                return NotFound();
            }

            var endereco = await _enderecoService.ObterPorId((int)id);

            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);
        }

        // GET: Enderecos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Enderecos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cep,Logradouro,Bairro,Localidade")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                await _enderecoService.Adicionar(endereco);

                var currentUser = User.Identity.Name;
                var user = _usuarioService.ObterTodos().Result.Find(u => u.Email == currentUser);

                if (user != null)
                {
                    user.EnderecoId = endereco.Id;
                    user.Endereco = endereco;
                    await _usuarioService.Editar(user);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(endereco);
        }

        // GET: Enderecos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || await _enderecoService.ObterTodos() == null)
            {
                return NotFound();
            }

            var endereco = await _enderecoService.ObterPorId((int)id);

            if (endereco == null)
            {
                return NotFound();
            }
            return View(endereco);
        }

        // POST: Enderecos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cep,Logradouro,Bairro,Localidade")] Endereco endereco)
        {
            if (id != endereco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _enderecoService.Editar(endereco);

                    var currentUser = User.Identity.Name;
                    var user = _usuarioService.ObterTodos().Result.Find(u => u.Email == currentUser);

                    if (user != null)
                    {
                        user.EnderecoId = endereco.Id;
                        user.Endereco = endereco;
                        await _usuarioService.Editar(user);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnderecoExists(endereco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(endereco);
        }

        // GET: Enderecos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || await _enderecoService.ObterTodos() == null)
            {
                return NotFound();
            }

            var endereco = await _enderecoService.ObterPorId((int)id);

            if (endereco == null)
            {
                return NotFound();
            }

            return View(endereco);
        }

        // POST: Enderecos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await _enderecoService.ObterTodos() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Endereco'  is null.");
            }
            var endereco = await _enderecoService.ObterPorId(id);
            if (endereco != null)
            {
                await _enderecoService.Deletar(endereco);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool EnderecoExists(int id)
        {
            var enderecos = _enderecoService.ObterTodos().Result;
            return enderecos.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult GetAddressDetails(string cep)
        {
            if (cep.Length == 8)
            {
                var httpClient = _httpClientFactory.CreateClient("ViaCep");
                var apiEndpoint = $"ws/{cep}/json";

                var response = httpClient.GetAsync(apiEndpoint).Result;

                if (response.IsSuccessStatusCode)
                {
                    var content = response.Content.ReadAsStringAsync().Result;
                    var addressDetails = JsonConvert.DeserializeObject<Endereco>(content);

                    return Json(addressDetails);
                }
            }

            return Json(null);
        }
    }
}

rede-social-de-carros/Views/Enderecos/Create.cshtml
@model rede_social_de_carros.Models.Endereco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Endereco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="enderecoForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="Cep" class="form-control" id="cepInput" />
                    <button type="button" class="btn btn-primary" onclick="fillAddress()">Preencher Dados</button>
                </div>
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label"></label>
                <input asp-for="Logradouro" class="form-control" id="logradouroInput" />
                <span asp-validation-for="Logradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" id="bairroInput" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidade" class="control-label"></label>
                <input asp-for="Localidade" class="form-control" id="localidadeInput" />
                <span asp-validation-for="Localidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function fillAddress() {
            const cep = document.getElementById('cepInput').value;

            if (cep.length === 8) {
                $.ajax({
                    url: '@Url.Action("GetAddressDetails", "Enderecos")',
                    type: 'GET',
                    data: { cep: cep },
                    success: function (data) {
                        if (data !== null) {
                            document.getElementById('logradouroInput').value = data.logradouro;
                            document.getElementById('bairroInput').value = data.bairro;
                            document.getElementById('localidadeInput').value = data.localidade;
                        }
                    }
                });
            }
        }
    </script>
}

rede-social-de-carros/Views/Enderecos/Delete.cshtml
@model rede_social_de_carros.Models.Endereco

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Endereco</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Logradouro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Localidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Localidade)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

rede-social-de-carros/Views/Enderecos/Details.cshtml
@model rede_social_de_carros.Models.Endereco

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Endereco</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Logradouro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Localidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Localidade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

rede-social-de-carros/Views/Enderecos/Edit.cshtml
@model rede_social_de_carros.Models.Endereco

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Endereco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <div class="input-group">
                    <input asp-for="Cep" class="form-control" id="cepInput" />
                    <button type="button" class="btn btn-primary" onclick="fillAddress()">Preencher Dados</button>
                </div>
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logradouro" class="control-label"></label>
                <input asp-for="Logradouro" class="form-control" id="logradouroInput" />
                <span asp-validation-for="Logradouro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bairro" class="control-label"></label>
                <input asp-for="Bairro" class="form-control" id="bairroInput" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidade" class="control-label"></label>
                <input asp-for="Localidade" class="form-control" id="localidadeInput" />
                <span asp-validation-for="Localidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function fillAddress() {
            const cep = document.getElementById('cepInput').value;

            if (cep.length === 8) {
                $.ajax({
                    url: '@Url.Action("GetAddressDetails", "Enderecos")',
                    type: 'GET',
                    data: { cep: cep },
                    success: function (data) {
                        if (data !== null) {
                            document.getElementById('logradouroInput').value = data.logradouro;
                            document.getElementById('bairroInput').value = data.bairro;
                            document.getElementById('localidadeInput').value = data.localidade;
                        }
                    }
                });
            }
        }
    </script>
}

rede-social-de-carros/Views/Enderecos/Index.cshtml
@model IEnumerable<rede_social_de_carros.Models.Endereco>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logradouro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Localidade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cep)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Logradouro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Localidade)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>